version: 2.1

commands:
  sayhello:
    steps:
      - run: echo "Hello from say hello"

jobs:
  custom-test:
    docker:
      - image: cimg/base:current
    resource_class: small

    steps:
      - checkout
      - run: echo "hello this is from central-template-orb"
      - run: echo "hoooa"
